backend:
  name: git-gateway
  repo: https://github.com/Stepheeeen/sdijieandassociates
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - label: "Home"
    name: "home"
    file: "content/pages/home.json"
    fields:
      - label: "Parallax Section"
        name: "parallax"
        widget: "object"
        fields:
          - label: "Background Image"
            name: "background"
            widget: "image"
          - label: "Overlay Opacity"
            name: "overlay"
            widget: "number"
            value_type: "int"
          - label: "Icon"
            name: "icon"
            widget: "string"
          - label: "Tagline"
            name: "tagline"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"

      - label: "About Section"
        name: "about"
        widget: "object"
        fields:
          - label: "Icon"
            name: "icon"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Key Points"
            name: "points"
            widget: "list"
            field:
              label: "Point"
              name: "point"
              widget: "string"
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Years of Experience"
            name: "years"
            widget: "number"
          - label: "Experience Text"
            name: "yearsText"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"

      - label: "Case Study Section"
        name: "caseStudy"
        widget: "object"
        fields:
          - label: "Icon"
            name: "icon"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Case Studies"
            name: "cases"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Image Alt"
                name: "alt"
                widget: "string"
              - label: "Case Link"
                name: "link"
                widget: "string"

  - label: "About"
    name: "about"
    file: "content/pages/about.json"
    fields:
      - label: "Name"
        name: "about.name"
        widget: "string"
      - label: "Description"
        name: "about.description"
        widget: "text"
      - label: "Experience Years"
        name: "about.experience.years"
        widget: "number"
      - label: "Experience Text"
        name: "about.experience.text"
        widget: "string"
      - label: "Image"
        name: "about.image"
        widget: "image"
      - label: "Image Alt"
        name: "about.alt"
        widget: "string"
      - label: "Highlights"
        name: "about.highlights"
        widget: "list"
        field:
          label: "Highlight"
          name: "highlight"
          widget: "string"
      - label: "Icon"
        name: "about2.icon"
        widget: "string"
      - label: "Subtitle"
        name: "about2.subtitle"
        widget: "string"
      - label: "Title"
        name: "about2.title"
        widget: "string"
      - label: "Description"
        name: "about2.description"
        widget: "markdown"
      - label: "Image"
        name: "about2.image"
        widget: "image"
      - label: "Image Alt"
        name: "about2.imageAlt"
        widget: "string"
      - label: "Founder Name"
        name: "about2.founderName"
        widget: "string"
      - label: "Founder Role"
        name: "about2.founderRole"
        widget: "string"

  - label: "Cases"
    name: "cases"
    file: "content/pages/cases.json"
    fields:
      - label: "Case List"
        name: "cases"
        widget: "list"
        fields:
          - label: "ID"
            name: "id"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
            media_library:
              config:
                multiple: false

  - label: "Case Studies"
    name: "case_studies"
    file: "content/pages/caseStudy.json"
    fields:
      - label: "Cases"
        name: "cases"
        widget: "list"
        fields:
          - label: "Case ID"
            name: "id"
            widget: "string"
          - label: "Case Study Title"
            name: "case_study"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Help Text"
            name: "help_text"
            widget: "string"
          - label: "Services"
            name: "services"
            widget: "list"
            field:
              label: "Service"
              name: "service"
              widget: "string"
          - label: "Notable Case"
            name: "notable_case"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"
          - label: "Call to Action"
            name: "cta"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"
