backend:
  name: github
  repo: https://github.com/Stepheeeen/sdijieandassociates
  branch: main

media_folder: "/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "Practice Areas"
        name: "practice"
        file: "practice-areas.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "Notable Cases"
        name: "notable-cases"
        file: "case-study-notable-cases.html" # ✅ Ensure the `file` is present
        fields:
          - { label: "Title", name: "title", widget: "string" } # ✅ Ensure `fields` is present
