backend:
  name: git-gateway
  repo: Stepheeeen/sdijieandassociates
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.json"
        fields:
          - label: "Parallax Section"
            name: "parallax"
            widget: "object"
            fields:
              - label: "Tagline"
                name: "tagline"
                widget: "string"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Button Text"
                name: "buttonText"
                widget: "string"
              - label: "Button Link"
                name: "buttonLink"
                widget: "string"

  - label: "About"
    name: "about"
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.json"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Experience Years"
            name: "experience_years"
            widget: "number"
          - label: "Experience Text"
            name: "experience_text"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Image Alt"
            name: "image_alt"
            widget: "string"
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            field:
              label: "Highlight"
              name: "highlight"
              widget: "string"

  - label: "About Section 2"
    name: "about2"
    files:
      - label: "About Section 2"
        name: "about2"
        file: "content/pages/about2.json"
        fields:
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "markdown"
          - label: "Founder Name"
            name: "founder_name"
            widget: "string"
          - label: "Founder Role"
            name: "founder_role"
            widget: "string"

  - label: "Cases"
    name: "cases"
    files:
      - label: "Cases Page"
        name: "cases"
        file: "content/pages/cases.json"
        fields:
          - label: "Case List"
            name: "cases"
            widget: "list"
            fields:
              - label: "ID"
                name: "id"
                widget: "string"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
                media_library:
                  config:
                    multiple: false

  - label: "Case Studies"
    name: "case_studies"
    files:
      - label: "Case Studies Page"
        name: "case_study"
        file: "content/pages/caseStudy.json"
        fields:
          - label: "Cases"
            name: "cases"
            widget: "list"
            fields:
              - label: "Case ID"
                name: "id"
                widget: "string"
              - label: "Case Study Title"
                name: "case_study"
                widget: "string"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"
              - label: "Help Text"
                name: "help_text"
                widget: "string"
              - label: "Services"
                name: "services"
                widget: "list"
                field:
                  label: "Service"
                  name: "service"
                  widget: "string"
              - label: "Notable Case"
                name: "notable_case"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "text"
              - label: "Call to Action"
                name: "cta"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "text"
